.TH MYSCREEN 1 "" "MyScreen User Manuals"
.SH NAME
.PP
myscreen - run GNU/Screen providing tab bar and several system
statistics
.SH SYNOPSIS
.PP
\f[B]myscreen\f[] [ \f[B]restart\f[] | \f[B]stop\f[] ] [
\f[B]screen_options\f[] ]
.SH DESCRIPTION
.PP
\f[I]MyScreen\f[] is a program that runs GNU/Screen adding a tab
bar and running myscreen-stats in order to display system
statistics.
It is written in C and it is expected to consume very few
resources.
.PP
\f[B]MyScreen\f[] includes one GNU/Screen configuration file and
myscreen-stats binary.
The configuration file of GNU/Screen allows to enable hardstatus
bar (at the bottom of the screen) in the manner of tab support in
certain graphical terminal emulators.
.PP
The myscreen-stats program provides several informations like the
number of users connected, the uptime, the upload and download
rates, the battery state, the wifi quality, the loadaverage, the
number of processes, the cpus rates, the disks rates, the ram and
swap percentages.
.PP
\f[B]To configure myscreen, you should copy /etc/myscreenrc file to ~/.myscreenrc\f[]
.SH COMMANDS
.PP
\f[I]MyScreen\f[] accepts the following commands:
.IP \[bu] 2
\f[B]restart\f[]: Restart the generation of stats (reloading the
configuration file).
.IP \[bu] 2
\f[B]stop\f[]: Stop the stats generation.
.SH COMMAND-LINE OPTIONS
.PP
All options are passed to GNU/Screen (see screen(1) for details).
.SH MODULES
.PP
\f[I]MyScreen\f[] is composed of modules:
.IP \[bu] 2
\f[B]Users\f[]: number of users connected (using
\f[I]getutent()\f[]).
.IP \[bu] 2
\f[B]Uptime\f[]: uptime of the system (using
\f[I]sysinfo()\f[]).
.PD 0
.P
.PD

.IP \[bu] 2
\f[B]Network\f[]: upload (^[rate] [unit]) and download rates
(v[rate] [unit]).
When myscreen starts or when you reload it, the selected device is
displayed.
Rates are calculated with /proc/net/dev file and device is selected
with /proc/net/route file.
.IP \[bu] 2
\f[B]Battery\f[]: battery level and charging state.
\f[I]S|PERCENTAGE%\f[] ; S can be a `"' (Full) without percentage,
a `_' (Discharging), or a `~' (Charging).
Percentage and state are determinated with
\f[I]/sys/class/power_supply/BAT0/uevent\f[] file.
.IP \[bu] 2
\f[B]Wifi\f[]: wifi signal quality percentage.
Quality is provided by \f[I]/proc/net/wireless\f[] file.
.IP \[bu] 2
\f[B]Reboot\f[]: `\@' (blinking if supported) if a reboot is
required.
It tests the existence of \f[I]/var/run/reboot-required\f[] file.
.IP \[bu] 2
\f[B]Loadaverage\f[]: load average.
(using \f[I]sysinfo()\f[] function)
.IP \[bu] 2
\f[B]Processes\f[]: number of processes.
(using \f[I]sysinfo()\f[])
.IP \[bu] 2
\f[B]Cpu\f[]: cpu rates : \f[I]average%(cpu0%,cpu1%,\&...)\f[].
Percentages are calculated with /proc/stat file.
Rates include user space and kernel mode cpu time.
.IP \[bu] 2
\f[B]Disks access\f[]: rates (read & write).
If there is no activity detected, it displays the device name.
(using \f[I]/proc/diskstats\f[] file)
.IP \[bu] 2
\f[B]Disks used space\f[]: used space of mounted partitions.
.IP \[bu] 2
\f[B]Ram\f[]: percentage of used ram without cache.
(using \f[I]sysinfo()\f[])
.IP \[bu] 2
\f[B]Swap\f[]: percentage of used swap if activated.
(using \f[I]sysinfo()\f[])
.SH FILES
.PP
\f[B]/etc/myscreenrc\f[] configuration of \f[I]myscreen\f[]
\f[B]$HOME/.myscreenrc\f[] read instead of /etc/myscreenrc
\f[B]/etc/myscreen-screenrc\f[] screen configuration file.
.SH SEE ALSO
.PP
\f[B]screen (1)\f[]
.SH AUTHORS
.PP
MyScreen was first developed by Clément Mondon
<clement.mondon@gmail.com>.
.PP
This manual page was written by Clément Mondon
<clement.mondon@gmail.com>, for the Debian project (and may be used
by others).

